server:
  port: 8011

spring:
  application:
    name: common

#  cloud:
#    client:
#      hostname: localhost

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka,http://localhost2:8762/eureka
#  instance:
#    appname: common
